import PublicFooter from "../components/PublicFooter";
import PublicHeader from "../components/PublicHeader";
import AboutHomeButton from "./AboutHomeButton";
import AboutRevealClient from "./AboutRevealClient";
import { createPublicMetadata } from "../../lib/seo/public-metadata";
import "../[ciudad]/ciudad.css";
import "./nosotros.css";

export const metadata = createPublicMetadata({
  title: "Nosotros",
  description: "Guía Educativa Tucumán nació para reunir en un solo lugar toda la oferta educativa de la provincia y acercar a cada persona a su próximo paso.",
  path: "/nosotros",
});

export default function AboutPage() {
  return <div className="app-shell">
    <PublicHeader />
    <AboutRevealClient />
    <section id="aboutPage" className="page active"><div className="about-page">
      <section className="about-hero about-block about-reveal"><div><span className="eyebrow">Nuestro propósito</span><h1>Todo gran futuro comienza con una decisión.</h1><div className="about-hero-text"><p>Miles de personas buscan todos los días una oportunidad para estudiar, cambiar de carrera o aprender algo nuevo. Sin embargo, encontrar la información correcta muchas veces no es fácil.</p><p>Guía Educativa Tucumán nació para reunir en un solo lugar toda la oferta educativa de la provincia y acercar a cada persona a su próximo paso.</p></div></div><div className="about-hero-visual"><img className="about-hero-image" src="https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&w=1000&q=82" alt="Estudiantes compartiendo ideas en un entorno educativo" /><div className="about-future-card"><span><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="m4 10 8-4 8 4-8 4Z" /><path d="M7 12v5c3 2 7 2 10 0v-5" /></svg></span><strong>Tu próximo paso</strong><small>Información clara para elegir con más confianza.</small></div></div></section>
      <section className="about-block about-reveal"><div className="about-heading"><span className="eyebrow">El camino</span><h2>Nuestra historia</h2></div><div className="about-timeline"><article className="about-step"><span className="about-step-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><circle cx="12" cy="8" r="4" /><path d="M5 21a7 7 0 0 1 14 0" /><path d="M19 4v5M16.5 6.5h5" /></svg></span><span className="about-step-number">Paso 1</span><h3>Todo empieza con una idea.</h3><p>Una persona quiere estudiar. No sabe dónde hacerlo ni qué opciones existen.</p></article><article className="about-step"><span className="about-step-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M4 6h16M4 12h10M4 18h16" /><circle cx="18" cy="12" r="2" /></svg></span><span className="about-step-number">Paso 2</span><h3>Nosotros organizamos el camino.</h3><p>Reunimos universidades, institutos, carreras, cursos, eventos y capacitaciones en una sola plataforma.</p></article><article className="about-step"><span className="about-step-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M5 19 19 5" /><path d="M10 5h9v9" /><path d="M5 8v11h11" /></svg></span><span className="about-step-number">Paso 3</span><h3>Vos elegís tu futuro.</h3><p>Cuando encontrar información deja de ser un problema, tomar una decisión se vuelve mucho más fácil.</p></article></div></section>
      <section className="about-block about-reveal"><div className="about-heading"><span className="eyebrow">GET para vos</span><h2>¿Por qué existe GET?</h2></div><div className="about-benefits"><article className="about-benefit"><span className="about-benefit-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M3 21h18" /><path d="M5 21V9l7-4 7 4v12" /><path d="M9 21v-6h6v6" /></svg></span><h3>Toda la oferta educativa</h3><p>Universidades, institutos, carreras y cursos en un solo lugar.</p></article><article className="about-benefit"><span className="about-benefit-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><circle cx="12" cy="12" r="9" /><path d="m8 12 2.5 2.5L16 9" /></svg></span><h3>Elegí con confianza</h3><p>Compará instituciones y encontrá la opción que mejor se adapte a vos.</p></article><article className="about-benefit"><span className="about-benefit-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><rect x="3" y="5" width="18" height="16" rx="2" /><path d="M8 3v4M16 3v4M3 10h18" /><path d="m9 15 2 2 4-4" /></svg></span><h3>Nunca te pierdas una oportunidad</h3><p>Eventos, ferias, exposiciones y capacitaciones siempre actualizados.</p></article><article className="about-benefit"><span className="about-benefit-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M12 21a9 9 0 1 0-9-9" /><path d="M3 16v5h5" /><path d="M8 12h8M12 8v8" /></svg></span><h3>Pensada para las personas</h3><p>Una plataforma simple, rápida y gratuita para quienes quieren seguir creciendo.</p></article></div></section>
      <section className="about-mission about-block about-reveal"><span className="about-mission-mark">“</span><blockquote>No creemos que las oportunidades deban encontrarse por casualidad.<br /><br />Creemos que deben estar al alcance de cualquier persona.</blockquote></section>
      <section className="about-closing about-block about-reveal"><img className="about-closing-image" src="https://images.unsplash.com/photo-1523580846011-d3a5bc25702b?auto=format&fit=crop&w=1800&q=85" alt="Estudiantes avanzando juntos hacia una nueva etapa" /><div className="about-closing-overlay" aria-hidden="true" /><div className="about-closing-content"><h2>Hoy buscás una carrera.<br />Mañana puede ser el comienzo de una nueva vida.</h2><AboutHomeButton /></div></section>
    </div></section>
    <PublicFooter />
  </div>;
}
