-- GET public catalog v1: canonical data seed.
-- This migration is intentionally non-idempotent: uniqueness violations must expose drift.
-- The legacy summary slug licenciatura-en-administracion maps to the canonical career master lic-en-administracion.
-- institutions[].careers is derived data and is not inserted as an aggregate.

insert into public.cities (
  slug, name, title, display_order, is_active, visual_metadata
) values
  ('concepcion', 'Concepción', 'Instituciones de Concepción', 1, true, '{"institutionIds":["universidad-siglo-21-concepcion","instituto-santa-barbara-concepcion","ies-concepcion-concepcion"],"featuredInstitutionIds":["universidad-siglo-21-concepcion","instituto-santa-barbara-concepcion","instituto-del-sur-monteros"],"canonicalDataNotice":"inconsistencia canónica conservada temporalmente para mantener fidelidad visual"}'::jsonb),
  ('monteros', 'Monteros', 'Instituciones de Monteros', 2, true, '{"institutionIds":["universidad-siglo-21-monteros","instituto-del-sur-monteros","centro-de-formacion-tucuman-monteros","instituto-san-miguel-monteros"],"featuredInstitutionIds":["universidad-siglo-21-monteros","instituto-santa-barbara-concepcion","instituto-del-sur-monteros"]}'::jsonb),
  ('aguilares', 'Aguilares', 'Instituciones de Aguilares', 3, true, '{"institutionIds":["universidad-siglo-21-aguilares","instituto-santa-barbara-aguilares","academia-profesional-norte-aguilares"],"featuredInstitutionIds":["universidad-siglo-21-aguilares","instituto-santa-barbara-aguilares","instituto-del-sur-monteros"],"canonicalDataNotice":"slider/fallback canónico preservado: incluye Instituto del Sur de Monteros"}'::jsonb);

insert into public.institutions (
  legacy_key, city_id, slug, name, type, logo_text, plan, slogan, description,
  address, whatsapp, hero_image_url, media_label, gallery, cities_label,
  display_order, is_featured, is_active, visual_metadata
)
select
  seed.legacy_key, cities.id, seed.slug, seed.name, seed.type, seed.logo_text,
  seed.plan, seed.slogan, seed.description, seed.address, seed.whatsapp,
  seed.hero_image_url, seed.media_label, seed.gallery, seed.cities_label,
  seed.display_order, seed.is_featured, seed.is_active, seed.visual_metadata
from (values
  ('universidad-siglo-21-concepcion', 'concepcion', 'universidad-siglo-21', 'Universidad Siglo 21', 'Privada', 'US21', 'Premium', 'Estudiá con flexibilidad y proyectá tu carrera desde Tucumán.', 'Educación innovadora, profesional y conectada con el mundo.', 'San Martín 124, Concepción', '3865 41 2020', 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?auto=format&fit=crop&w=1200&q=80', 'Video institucional', '["https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1523580846011-d3a5bc25702b?auto=format&fit=crop&w=1200&q=80"]'::jsonb, '["Concepción","Monteros","Aguilares"]'::jsonb, 1, true, true, '{}'::jsonb),
  ('universidad-siglo-21-monteros', 'monteros', 'universidad-siglo-21', 'Universidad Siglo 21', 'Privada', 'US21', 'Premium', 'Estudiá con flexibilidad y proyectá tu carrera desde Tucumán.', 'Educación innovadora, profesional y conectada con el mundo.', 'San Martín 124, Concepción', '3865 41 2020', 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?auto=format&fit=crop&w=1200&q=80', 'Video institucional', '["https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1523580846011-d3a5bc25702b?auto=format&fit=crop&w=1200&q=80"]'::jsonb, '["Concepción","Monteros","Aguilares"]'::jsonb, 1, true, true, '{}'::jsonb),
  ('instituto-santa-barbara-concepcion', 'concepcion', 'instituto-santa-barbara', 'Instituto Santa Bárbara', 'Terciario Privado', 'ISB', 'Premium', 'Formación técnica para integrarte rápido al mundo laboral.', 'Formación terciaria con valores, prácticas y salida laboral.', 'Belgrano 810, Aguilares', '3865 55 1188', 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=1200&q=80', 'Video institucional', '["https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1523580846011-d3a5bc25702b?auto=format&fit=crop&w=1200&q=80"]'::jsonb, '["Concepción","Aguilares"]'::jsonb, 2, true, true, '{"canonicalDataNotice":"inconsistencia canónica conservada temporalmente para mantener fidelidad con la demo"}'::jsonb),
  ('universidad-siglo-21-aguilares', 'aguilares', 'universidad-siglo-21', 'Universidad Siglo 21', 'Privada', 'US21', 'Premium', 'Estudiá con flexibilidad y proyectá tu carrera desde Tucumán.', 'Educación innovadora, profesional y conectada con el mundo.', 'San Martín 124, Concepción', '3865 41 2020', 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?auto=format&fit=crop&w=1200&q=80', 'Video institucional', '["https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1523580846011-d3a5bc25702b?auto=format&fit=crop&w=1200&q=80"]'::jsonb, '["Concepción","Monteros","Aguilares"]'::jsonb, 1, true, true, '{}'::jsonb),
  ('instituto-santa-barbara-aguilares', 'aguilares', 'instituto-santa-barbara', 'Instituto Santa Bárbara', 'Terciario Privado', 'ISB', 'Premium', 'Formación técnica para integrarte rápido al mundo laboral.', 'Formación terciaria con valores, prácticas y salida laboral.', 'Belgrano 810, Aguilares', '3865 55 1188', 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=1200&q=80', 'Video institucional', '["https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1523580846011-d3a5bc25702b?auto=format&fit=crop&w=1200&q=80"]'::jsonb, '["Concepción","Aguilares"]'::jsonb, 2, true, true, '{}'::jsonb),
  ('academia-profesional-norte-aguilares', 'aguilares', 'academia-profesional-norte', 'Academia Profesional Norte', 'Academia', 'APN', 'Básico', 'Capacitaciones digitales para empezar a trabajar.', 'Cursos prácticos de diseño, redes sociales, ventas y herramientas digitales.', 'Moreno 575, Aguilares', '3865 60 7711', 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80', 'Video de alumnos', '["https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1523580846011-d3a5bc25702b?auto=format&fit=crop&w=1200&q=80"]'::jsonb, '["Aguilares"]'::jsonb, 3, false, true, '{}'::jsonb),
  ('instituto-del-sur-monteros', 'monteros', 'instituto-del-sur', 'Instituto del Sur', 'Terciario', 'IDS', 'Profesional', 'Tecnicaturas orientadas a una salida laboral concreta.', 'Formación técnica y profesional en áreas comerciales, administrativas y digitales.', 'Av. Mitre 420, Concepción', '3865 44 8712', 'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&w=1200&q=80', 'Video de carreras', '["https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1523580846011-d3a5bc25702b?auto=format&fit=crop&w=1200&q=80"]'::jsonb, '["Monteros"]'::jsonb, 2, true, true, '{}'::jsonb),
  ('centro-de-formacion-tucuman-monteros', 'monteros', 'centro-de-formacion-tucuman', 'Centro de Formación Tucumán', 'Capacitación', 'CFT', 'Básico', 'Cursos cortos para fortalecer tu perfil laboral.', 'Capacitaciones prácticas para jóvenes y adultos que buscan ampliar oportunidades.', 'Rivadavia 295, Monteros', '3863 40 2100', 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=1200&q=80', 'Imagen superior', '["https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1523580846011-d3a5bc25702b?auto=format&fit=crop&w=1200&q=80"]'::jsonb, '["Monteros"]'::jsonb, 3, false, true, '{}'::jsonb),
  ('instituto-san-miguel-monteros', 'monteros', 'instituto-san-miguel', 'Instituto San Miguel', 'Instituto', 'ISM', 'Profesional', 'Educación cercana para acompañar vocaciones de servicio.', 'Propuestas presenciales y a distancia vinculadas a educación, salud y comunidad.', 'Laprida 660, Monteros', '3863 47 6400', 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1200&q=80', 'Imagen superior', '["https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1523580846011-d3a5bc25702b?auto=format&fit=crop&w=1200&q=80"]'::jsonb, '["Monteros"]'::jsonb, 4, false, true, '{}'::jsonb),
  ('ies-concepcion-concepcion', 'concepcion', 'ies-concepcion', 'IES Concepción', 'Público', 'IES', 'Básico', 'Educación pública, gratuita y de calidad para todos.', 'Educación pública, gratuita y de calidad para todos.', 'España 320, Concepción', '3865 50 3300', 'https://images.unsplash.com/photo-1568792923760-d70635a89fdc?auto=format&fit=crop&w=1200&q=80', 'Imagen superior', '["https://images.unsplash.com/photo-1568792923760-d70635a89fdc?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1523580846011-d3a5bc25702b?auto=format&fit=crop&w=1200&q=80"]'::jsonb, '["Concepción"]'::jsonb, 3, false, true, '{}'::jsonb)
) as seed(
  legacy_key, city_slug, slug, name, type, logo_text, plan, slogan, description,
  address, whatsapp, hero_image_url, media_label, gallery, cities_label,
  display_order, is_featured, is_active, visual_metadata
)
join public.cities on cities.slug = seed.city_slug;

-- Career sources do not define publication fields; approved schema defaults are materialized explicitly.
insert into public.career_masters (
  legacy_key, slug, name, description, graduate_profile, work_field,
  study_plan, requirements, faq, status, is_active
) values
  ('profesorado-ingles', 'profesorado-ingles', 'Profesorado de Inglés', 'Formación pedagógica y práctica del idioma.', 'Profesional preparado para aplicar conocimientos y desarrollarse en su área.', 'Ámbitos públicos y privados relacionados con la formación profesional.', '["Primer año","Segundo año","Tercer año"]'::jsonb, '["DNI","Título secundario","Formulario de inscripción"]'::jsonb, '[{"question":"¿Cuándo comienzan las inscripciones?","answer":"Consultá con la institución para conocer las próximas fechas."},{"question":"¿Cómo solicito más información?","answer":"Podés utilizar WhatsApp o el formulario de esta página."}]'::jsonb, 'published', true),
  ('tecnicatura-administracion', 'tecnicatura-administracion', 'Tecnicatura en Administración', 'Gestión administrativa para organizaciones públicas y privadas.', 'Profesional preparado para aplicar conocimientos y desarrollarse en su área.', 'Ámbitos públicos y privados relacionados con la formación profesional.', '["Primer año","Segundo año","Tercer año"]'::jsonb, '["DNI","Título secundario","Formulario de inscripción"]'::jsonb, '[{"question":"¿Cuándo comienzan las inscripciones?","answer":"Consultá con la institución para conocer las próximas fechas."},{"question":"¿Cómo solicito más información?","answer":"Podés utilizar WhatsApp o el formulario de esta página."}]'::jsonb, 'published', true),
  ('profesorado-educacion-primaria', 'profesorado-educacion-primaria', 'Profesorado de Educación Primaria', 'Formación docente para nivel primario.', 'Profesional preparado para aplicar conocimientos y desarrollarse en su área.', 'Ámbitos públicos y privados relacionados con la formación profesional.', '["Primer año","Segundo año","Tercer año"]'::jsonb, '["DNI","Título secundario","Formulario de inscripción"]'::jsonb, '[{"question":"¿Cuándo comienzan las inscripciones?","answer":"Consultá con la institución para conocer las próximas fechas."},{"question":"¿Cómo solicito más información?","answer":"Podés utilizar WhatsApp o el formulario de esta página."}]'::jsonb, 'published', true),
  ('diagnostico-por-imagenes', 'diagnostico-por-imagenes', 'Diagnóstico por Imágenes', 'Formación en tecnología aplicada a estudios médicos.', 'Profesional preparado para aplicar conocimientos y desarrollarse en su área.', 'Ámbitos públicos y privados relacionados con la formación profesional.', '["Primer año","Segundo año","Tercer año"]'::jsonb, '["DNI","Título secundario","Formulario de inscripción"]'::jsonb, '[{"question":"¿Cuándo comienzan las inscripciones?","answer":"Consultá con la institución para conocer las próximas fechas."},{"question":"¿Cómo solicito más información?","answer":"Podés utilizar WhatsApp o el formulario de esta página."}]'::jsonb, 'published', true),
  ('laboratorio-de-analisis-clinicos', 'laboratorio-de-analisis-clinicos', 'Laboratorio de Análisis Clínicos', 'Técnicas de laboratorio, muestras y protocolos de calidad.', 'Profesional preparado para aplicar conocimientos y desarrollarse en su área.', 'Ámbitos públicos y privados relacionados con la formación profesional.', '["Primer año","Segundo año","Tercer año"]'::jsonb, '["DNI","Título secundario","Formulario de inscripción"]'::jsonb, '[{"question":"¿Cuándo comienzan las inscripciones?","answer":"Consultá con la institución para conocer las próximas fechas."},{"question":"¿Cómo solicito más información?","answer":"Podés utilizar WhatsApp o el formulario de esta página."}]'::jsonb, 'published', true),
  ('instrumentacion-quirurgica', 'instrumentacion-quirurgica', 'Instrumentación Quirúrgica', 'Capacitación para asistir procedimientos en ámbitos de salud.', 'Profesional preparado para aplicar conocimientos y desarrollarse en su área.', 'Ámbitos públicos y privados relacionados con la formación profesional.', '["Primer año","Segundo año","Tercer año"]'::jsonb, '["DNI","Título secundario","Formulario de inscripción"]'::jsonb, '[{"question":"¿Cuándo comienzan las inscripciones?","answer":"Consultá con la institución para conocer las próximas fechas."},{"question":"¿Cómo solicito más información?","answer":"Podés utilizar WhatsApp o el formulario de esta página."}]'::jsonb, 'published', true),
  ('abogacia', 'abogacia', 'Abogacía', 'Formación jurídica con modalidad flexible y acompañamiento tutorial.', 'Profesional preparado para aplicar conocimientos y desarrollarse en su área.', 'Ámbitos públicos y privados relacionados con la formación profesional.', '["Primer año","Segundo año","Tercer año"]'::jsonb, '["DNI","Título secundario","Formulario de inscripción"]'::jsonb, '[{"question":"¿Cuándo comienzan las inscripciones?","answer":"Consultá con la institución para conocer las próximas fechas."},{"question":"¿Cómo solicito más información?","answer":"Podés utilizar WhatsApp o el formulario de esta página."}]'::jsonb, 'published', true),
  ('contador-publico', 'contador-publico', 'Contador Público', 'Herramientas contables, impositivas y financieras para empresas.', 'Profesional preparado para aplicar conocimientos y desarrollarse en su área.', 'Ámbitos públicos y privados relacionados con la formación profesional.', '["Primer año","Segundo año","Tercer año"]'::jsonb, '["DNI","Título secundario","Formulario de inscripción"]'::jsonb, '[{"question":"¿Cuándo comienzan las inscripciones?","answer":"Consultá con la institución para conocer las próximas fechas."},{"question":"¿Cómo solicito más información?","answer":"Podés utilizar WhatsApp o el formulario de esta página."}]'::jsonb, 'published', true),
  ('lic-en-administracion', 'lic-en-administracion', 'Lic. en Administración', 'Gestión, liderazgo y estrategia para organizaciones actuales.', 'Profesional preparado para aplicar conocimientos y desarrollarse en su área.', 'Ámbitos públicos y privados relacionados con la formación profesional.', '["Primer año","Segundo año","Tercer año"]'::jsonb, '["DNI","Título secundario","Formulario de inscripción"]'::jsonb, '[{"question":"¿Cuándo comienzan las inscripciones?","answer":"Consultá con la institución para conocer las próximas fechas."},{"question":"¿Cómo solicito más información?","answer":"Podés utilizar WhatsApp o el formulario de esta página."}]'::jsonb, 'published', true),
  ('higiene-y-seguridad', 'higiene-y-seguridad', 'Higiene y Seguridad', 'Prevención, normativa y seguridad aplicada al trabajo.', 'Profesional preparado para aplicar conocimientos y desarrollarse en su área.', 'Ámbitos públicos y privados relacionados con la formación profesional.', '["Primer año","Segundo año","Tercer año"]'::jsonb, '["DNI","Título secundario","Formulario de inscripción"]'::jsonb, '[{"question":"¿Cuándo comienzan las inscripciones?","answer":"Consultá con la institución para conocer las próximas fechas."},{"question":"¿Cómo solicito más información?","answer":"Podés utilizar WhatsApp o el formulario de esta página."}]'::jsonb, 'published', true),
  ('marketing', 'marketing', 'Marketing', 'Planificación comercial, comunicación y campañas digitales.', 'Profesional preparado para aplicar conocimientos y desarrollarse en su área.', 'Ámbitos públicos y privados relacionados con la formación profesional.', '["Primer año","Segundo año","Tercer año"]'::jsonb, '["DNI","Título secundario","Formulario de inscripción"]'::jsonb, '[{"question":"¿Cuándo comienzan las inscripciones?","answer":"Consultá con la institución para conocer las próximas fechas."},{"question":"¿Cómo solicito más información?","answer":"Podés utilizar WhatsApp o el formulario de esta página."}]'::jsonb, 'published', true),
  ('recursos-humanos', 'recursos-humanos', 'Recursos Humanos', 'Selección, capacitación y gestión de equipos.', 'Profesional preparado para aplicar conocimientos y desarrollarse en su área.', 'Ámbitos públicos y privados relacionados con la formación profesional.', '["Primer año","Segundo año","Tercer año"]'::jsonb, '["DNI","Título secundario","Formulario de inscripción"]'::jsonb, '[{"question":"¿Cuándo comienzan las inscripciones?","answer":"Consultá con la institución para conocer las próximas fechas."},{"question":"¿Cómo solicito más información?","answer":"Podés utilizar WhatsApp o el formulario de esta página."}]'::jsonb, 'published', true),
  ('administracion-de-empresas', 'administracion-de-empresas', 'Administración de Empresas', 'Organización, procesos y gestión operativa.', 'Profesional preparado para aplicar conocimientos y desarrollarse en su área.', 'Ámbitos públicos y privados relacionados con la formación profesional.', '["Primer año","Segundo año","Tercer año"]'::jsonb, '["DNI","Título secundario","Formulario de inscripción"]'::jsonb, '[{"question":"¿Cuándo comienzan las inscripciones?","answer":"Consultá con la institución para conocer las próximas fechas."},{"question":"¿Cómo solicito más información?","answer":"Podés utilizar WhatsApp o el formulario de esta página."}]'::jsonb, 'published', true),
  ('profesorado', 'profesorado', 'Profesorado', 'Formación pedagógica con prácticas y acompañamiento.', 'Profesional preparado para aplicar conocimientos y desarrollarse en su área.', 'Ámbitos públicos y privados relacionados con la formación profesional.', '["Primer año","Segundo año","Tercer año"]'::jsonb, '["DNI","Título secundario","Formulario de inscripción"]'::jsonb, '[{"question":"¿Cuándo comienzan las inscripciones?","answer":"Consultá con la institución para conocer las próximas fechas."},{"question":"¿Cómo solicito más información?","answer":"Podés utilizar WhatsApp o el formulario de esta página."}]'::jsonb, 'published', true),
  ('gestion-educativa', 'gestion-educativa', 'Gestión Educativa', 'Herramientas para coordinar proyectos institucionales.', 'Profesional preparado para aplicar conocimientos y desarrollarse en su área.', 'Ámbitos públicos y privados relacionados con la formación profesional.', '["Primer año","Segundo año","Tercer año"]'::jsonb, '["DNI","Título secundario","Formulario de inscripción"]'::jsonb, '[{"question":"¿Cuándo comienzan las inscripciones?","answer":"Consultá con la institución para conocer las próximas fechas."},{"question":"¿Cómo solicito más información?","answer":"Podés utilizar WhatsApp o el formulario de esta página."}]'::jsonb, 'published', true),
  ('acompanante-terapeutico', 'acompanante-terapeutico', 'Acompañante Terapéutico', 'Intervención, apoyo y seguimiento en contextos de cuidado.', 'Profesional preparado para aplicar conocimientos y desarrollarse en su área.', 'Ámbitos públicos y privados relacionados con la formación profesional.', '["Primer año","Segundo año","Tercer año"]'::jsonb, '["DNI","Título secundario","Formulario de inscripción"]'::jsonb, '[{"question":"¿Cuándo comienzan las inscripciones?","answer":"Consultá con la institución para conocer las próximas fechas."},{"question":"¿Cómo solicito más información?","answer":"Podés utilizar WhatsApp o el formulario de esta página."}]'::jsonb, 'published', true),
  ('diseno-grafico', 'diseno-grafico', 'Diseño Gráfico', 'Piezas visuales, identidad y herramientas de diseño.', 'Profesional preparado para aplicar conocimientos y desarrollarse en su área.', 'Ámbitos públicos y privados relacionados con la formación profesional.', '["Primer año","Segundo año","Tercer año"]'::jsonb, '["DNI","Título secundario","Formulario de inscripción"]'::jsonb, '[{"question":"¿Cuándo comienzan las inscripciones?","answer":"Consultá con la institución para conocer las próximas fechas."},{"question":"¿Cómo solicito más información?","answer":"Podés utilizar WhatsApp o el formulario de esta página."}]'::jsonb, 'published', true),
  ('community-manager', 'community-manager', 'Community Manager', 'Planificación de contenido, redes y métricas.', 'Profesional preparado para aplicar conocimientos y desarrollarse en su área.', 'Ámbitos públicos y privados relacionados con la formación profesional.', '["Primer año","Segundo año","Tercer año"]'::jsonb, '["DNI","Título secundario","Formulario de inscripción"]'::jsonb, '[{"question":"¿Cuándo comienzan las inscripciones?","answer":"Consultá con la institución para conocer las próximas fechas."},{"question":"¿Cómo solicito más información?","answer":"Podés utilizar WhatsApp o el formulario de esta página."}]'::jsonb, 'published', true),
  ('ventas-digitales', 'ventas-digitales', 'Ventas Digitales', 'Embudo comercial, atención online y cierre de ventas.', 'Profesional preparado para aplicar conocimientos y desarrollarse en su área.', 'Ámbitos públicos y privados relacionados con la formación profesional.', '["Primer año","Segundo año","Tercer año"]'::jsonb, '["DNI","Título secundario","Formulario de inscripción"]'::jsonb, '[{"question":"¿Cuándo comienzan las inscripciones?","answer":"Consultá con la institución para conocer las próximas fechas."},{"question":"¿Cómo solicito más información?","answer":"Podés utilizar WhatsApp o el formulario de esta página."}]'::jsonb, 'published', true);

insert into public.academic_offerings (
  legacy_key, institution_id, career_master_id, modality, duration, degree,
  campus, shifts, national_validity, image_url, badge, display_order,
  form_enabled, whatsapp, is_visible, publication_status, metadata
)
select
  seed.legacy_key, institutions.id, career_masters.id, seed.modality,
  seed.duration, seed.degree, seed.campus, seed.shifts, seed.national_validity,
  seed.image_url, seed.badge, seed.display_order, seed.form_enabled, seed.whatsapp,
  seed.is_visible, seed.publication_status, seed.metadata
from (values
  ('ies-concepcion-concepcion-profesorado-ingles', 'ies-concepcion-concepcion', 'profesorado-ingles', 'Presencial', '3 años', 'Profesorado de Inglés', null, 'Consultar', 'Sí', 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=1200&q=80', 'Próximo ingreso', 3, true, null, true, 'published', '{}'::jsonb),
  ('ies-concepcion-concepcion-tecnicatura-administracion', 'ies-concepcion-concepcion', 'tecnicatura-administracion', 'Presencial', '3 años', 'Tecnicatura en Administración', null, 'Consultar', 'Sí', 'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&w=1200&q=80', 'Nueva carrera', 2, true, null, true, 'published', '{}'::jsonb),
  ('ies-concepcion-concepcion-profesorado-educacion-primaria', 'ies-concepcion-concepcion', 'profesorado-educacion-primaria', 'Presencial', '3 años', 'Profesorado de Educación Primaria', null, 'Consultar', 'Sí', 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1200&q=80', 'Inscripciones abiertas', 1, true, null, true, 'published', '{}'::jsonb),
  ('instituto-santa-barbara-concepcion-diagnostico-por-imagenes', 'instituto-santa-barbara-concepcion', 'diagnostico-por-imagenes', 'Presencial', '3 años', 'Diagnóstico por Imágenes', null, 'Consultar', 'Sí', 'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&w=1200&q=80', 'Próximo ingreso', 3, true, null, true, 'published', '{}'::jsonb),
  ('instituto-santa-barbara-concepcion-laboratorio-de-analisis-clinicos', 'instituto-santa-barbara-concepcion', 'laboratorio-de-analisis-clinicos', 'Presencial', '3 años', 'Laboratorio de Análisis Clínicos', null, 'Consultar', 'Sí', 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1200&q=80', 'Nueva carrera', 2, true, null, true, 'published', '{}'::jsonb),
  ('instituto-santa-barbara-concepcion-instrumentacion-quirurgica', 'instituto-santa-barbara-concepcion', 'instrumentacion-quirurgica', 'Presencial', '3 años', 'Instrumentación Quirúrgica', null, 'Consultar', 'Sí', 'https://images.unsplash.com/photo-1551076805-e1869033e561?auto=format&fit=crop&w=1200&q=80', 'Inscripciones abiertas', 1, true, null, true, 'published', '{}'::jsonb),
  ('universidad-siglo-21-concepcion-abogacia', 'universidad-siglo-21-concepcion', 'abogacia', 'Presencial', '3 años', 'Abogacía', null, 'Consultar', 'Sí', 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1200&q=80', 'Inscripciones abiertas', 1, true, null, true, 'published', '{}'::jsonb),
  ('universidad-siglo-21-monteros-abogacia', 'universidad-siglo-21-monteros', 'abogacia', 'Presencial', '3 años', 'Abogacía', null, 'Consultar', 'Sí', 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1200&q=80', 'Inscripciones abiertas', 1, true, null, true, 'published', '{}'::jsonb),
  ('universidad-siglo-21-concepcion-contador-publico', 'universidad-siglo-21-concepcion', 'contador-publico', 'Presencial', '3 años', 'Contador Público', null, 'Consultar', 'Sí', 'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&w=1200&q=80', 'Nueva carrera', 2, true, null, true, 'published', '{}'::jsonb),
  ('universidad-siglo-21-monteros-contador-publico', 'universidad-siglo-21-monteros', 'contador-publico', 'Presencial', '3 años', 'Contador Público', null, 'Consultar', 'Sí', 'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&w=1200&q=80', 'Nueva carrera', 2, true, null, true, 'published', '{}'::jsonb),
  ('universidad-siglo-21-concepcion-lic-en-administracion', 'universidad-siglo-21-concepcion', 'lic-en-administracion', 'Presencial', '3 años', 'Lic. en Administración', null, 'Consultar', 'Sí', 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80', 'Próximo ingreso', 3, true, null, true, 'published', '{}'::jsonb),
  ('universidad-siglo-21-monteros-lic-en-administracion', 'universidad-siglo-21-monteros', 'lic-en-administracion', 'Presencial', '3 años', 'Lic. en Administración', null, 'Consultar', 'Sí', 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80', 'Próximo ingreso', 3, true, null, true, 'published', '{}'::jsonb),
  ('universidad-siglo-21-concepcion-higiene-y-seguridad', 'universidad-siglo-21-concepcion', 'higiene-y-seguridad', 'Presencial', '3 años', 'Higiene y Seguridad', null, 'Consultar', 'Sí', 'https://images.unsplash.com/photo-1551076805-e1869033e561?auto=format&fit=crop&w=1200&q=80', 'Inscripciones abiertas', 4, true, null, true, 'published', '{}'::jsonb),
  ('universidad-siglo-21-monteros-higiene-y-seguridad', 'universidad-siglo-21-monteros', 'higiene-y-seguridad', 'Presencial', '3 años', 'Higiene y Seguridad', null, 'Consultar', 'Sí', 'https://images.unsplash.com/photo-1551076805-e1869033e561?auto=format&fit=crop&w=1200&q=80', 'Inscripciones abiertas', 4, true, null, true, 'published', '{}'::jsonb),
  ('instituto-del-sur-monteros-marketing', 'instituto-del-sur-monteros', 'marketing', 'Presencial', '3 años', 'Marketing', null, 'Consultar', 'Sí', 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80', 'Inscripciones abiertas', 1, true, null, true, 'published', '{}'::jsonb),
  ('instituto-del-sur-monteros-recursos-humanos', 'instituto-del-sur-monteros', 'recursos-humanos', 'Presencial', '3 años', 'Recursos Humanos', null, 'Consultar', 'Sí', 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=1200&q=80', 'Nueva carrera', 2, true, null, true, 'published', '{}'::jsonb),
  ('instituto-del-sur-monteros-administracion-de-empresas', 'instituto-del-sur-monteros', 'administracion-de-empresas', 'Presencial', '3 años', 'Administración de Empresas', null, 'Consultar', 'Sí', 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1200&q=80', 'Próximo ingreso', 3, true, null, true, 'published', '{}'::jsonb),
  ('instituto-san-miguel-monteros-profesorado', 'instituto-san-miguel-monteros', 'profesorado', 'Presencial', '3 años', 'Profesorado', null, 'Consultar', 'Sí', 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1200&q=80', 'Inscripciones abiertas', 1, true, null, true, 'published', '{}'::jsonb),
  ('instituto-san-miguel-monteros-gestion-educativa', 'instituto-san-miguel-monteros', 'gestion-educativa', 'Presencial', '3 años', 'Gestión Educativa', null, 'Consultar', 'Sí', 'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&w=1200&q=80', 'Nueva carrera', 2, true, null, true, 'published', '{}'::jsonb),
  ('instituto-san-miguel-monteros-acompanante-terapeutico', 'instituto-san-miguel-monteros', 'acompanante-terapeutico', 'Presencial', '3 años', 'Acompañante Terapéutico', null, 'Consultar', 'Sí', 'https://images.unsplash.com/photo-1551076805-e1869033e561?auto=format&fit=crop&w=1200&q=80', 'Próximo ingreso', 3, true, null, true, 'published', '{}'::jsonb),
  ('universidad-siglo-21-aguilares-abogacia', 'universidad-siglo-21-aguilares', 'abogacia', 'Presencial', '3 años', 'Abogacía', null, 'Consultar', 'Sí', 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1200&q=80', 'Inscripciones abiertas', 1, true, null, true, 'published', '{}'::jsonb),
  ('universidad-siglo-21-aguilares-contador-publico', 'universidad-siglo-21-aguilares', 'contador-publico', 'Presencial', '3 años', 'Contador Público', null, 'Consultar', 'Sí', 'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&w=1200&q=80', 'Nueva carrera', 2, true, null, true, 'published', '{}'::jsonb),
  ('universidad-siglo-21-aguilares-lic-en-administracion', 'universidad-siglo-21-aguilares', 'lic-en-administracion', 'Presencial', '3 años', 'Lic. en Administración', null, 'Consultar', 'Sí', 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80', 'Próximo ingreso', 3, true, null, true, 'published', '{}'::jsonb),
  ('universidad-siglo-21-aguilares-higiene-y-seguridad', 'universidad-siglo-21-aguilares', 'higiene-y-seguridad', 'Presencial', '3 años', 'Higiene y Seguridad', null, 'Consultar', 'Sí', 'https://images.unsplash.com/photo-1551076805-e1869033e561?auto=format&fit=crop&w=1200&q=80', 'Inscripciones abiertas', 4, true, null, true, 'published', '{}'::jsonb),
  ('instituto-santa-barbara-aguilares-instrumentacion-quirurgica', 'instituto-santa-barbara-aguilares', 'instrumentacion-quirurgica', 'Presencial', '3 años', 'Instrumentación Quirúrgica', null, 'Consultar', 'Sí', 'https://images.unsplash.com/photo-1551076805-e1869033e561?auto=format&fit=crop&w=1200&q=80', 'Inscripciones abiertas', 1, true, null, true, 'published', '{}'::jsonb),
  ('instituto-santa-barbara-aguilares-laboratorio-de-analisis-clinicos', 'instituto-santa-barbara-aguilares', 'laboratorio-de-analisis-clinicos', 'Presencial', '3 años', 'Laboratorio de Análisis Clínicos', null, 'Consultar', 'Sí', 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1200&q=80', 'Nueva carrera', 2, true, null, true, 'published', '{}'::jsonb),
  ('instituto-santa-barbara-aguilares-diagnostico-por-imagenes', 'instituto-santa-barbara-aguilares', 'diagnostico-por-imagenes', 'Presencial', '3 años', 'Diagnóstico por Imágenes', null, 'Consultar', 'Sí', 'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&w=1200&q=80', 'Próximo ingreso', 3, true, null, true, 'published', '{}'::jsonb),
  ('academia-profesional-norte-aguilares-diseno-grafico', 'academia-profesional-norte-aguilares', 'diseno-grafico', 'Presencial', '3 años', 'Diseño Gráfico', 'Moreno 575, Aguilares', 'Consultar', 'Sí', 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80', 'Inscripciones abiertas', 1, true, null, true, 'published', '{}'::jsonb),
  ('academia-profesional-norte-aguilares-community-manager', 'academia-profesional-norte-aguilares', 'community-manager', 'Presencial', '3 años', 'Community Manager', 'Moreno 575, Aguilares', 'Consultar', 'Sí', 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80', 'Nueva carrera', 2, true, null, true, 'published', '{}'::jsonb),
  ('academia-profesional-norte-aguilares-ventas-digitales', 'academia-profesional-norte-aguilares', 'ventas-digitales', 'Presencial', '3 años', 'Ventas Digitales', 'Moreno 575, Aguilares', 'Consultar', 'Sí', 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=1200&q=80', 'Próximo ingreso', 3, true, null, true, 'published', '{}'::jsonb)
) as seed(
  legacy_key, institution_legacy_key, career_slug, modality, duration, degree,
  campus, shifts, national_validity, image_url, badge, display_order,
  form_enabled, whatsapp, is_visible, publication_status, metadata
)
join public.institutions on institutions.legacy_key = seed.institution_legacy_key
join public.career_masters on career_masters.slug = seed.career_slug;

insert into public.training_programs (
  legacy_key, slug, name, description, profile, work_field, contents,
  requirements, faq, status, is_active
) values
  ('auxiliar-administrativo', 'auxiliar-administrativo', 'Auxiliar Administrativo', 'Tareas de oficina, atención y documentación comercial.', 'Profesional preparado para aplicar conocimientos y desarrollarse en su área.', 'Ámbitos públicos y privados relacionados con la formación profesional.', '["Primer año","Segundo año","Tercer año"]'::jsonb, '["DNI","Título secundario","Formulario de inscripción"]'::jsonb, '[{"question":"¿Cuándo comienzan las inscripciones?","answer":"Consultá con la institución para conocer las próximas fechas."},{"question":"¿Cómo solicito más información?","answer":"Podés utilizar WhatsApp o el formulario de esta página."}]'::jsonb, 'published', true),
  ('secretariado', 'secretariado', 'Secretariado', 'Organización, comunicación y soporte administrativo.', 'Profesional preparado para aplicar conocimientos y desarrollarse en su área.', 'Ámbitos públicos y privados relacionados con la formación profesional.', '["Primer año","Segundo año","Tercer año"]'::jsonb, '["DNI","Título secundario","Formulario de inscripción"]'::jsonb, '[{"question":"¿Cuándo comienzan las inscripciones?","answer":"Consultá con la institución para conocer las próximas fechas."},{"question":"¿Cómo solicito más información?","answer":"Podés utilizar WhatsApp o el formulario de esta página."}]'::jsonb, 'published', true),
  ('operador-de-pc', 'operador-de-pc', 'Operador de PC', 'Herramientas digitales esenciales para el trabajo.', 'Profesional preparado para aplicar conocimientos y desarrollarse en su área.', 'Ámbitos públicos y privados relacionados con la formación profesional.', '["Primer año","Segundo año","Tercer año"]'::jsonb, '["DNI","Título secundario","Formulario de inscripción"]'::jsonb, '[{"question":"¿Cuándo comienzan las inscripciones?","answer":"Consultá con la institución para conocer las próximas fechas."},{"question":"¿Cómo solicito más información?","answer":"Podés utilizar WhatsApp o el formulario de esta página."}]'::jsonb, 'published', true);

insert into public.training_offerings (
  legacy_key, institution_id, training_program_id, modality, duration,
  certification, campus, shifts, national_validity, image_url, badge,
  display_order, form_enabled, whatsapp, is_visible, publication_status, metadata
)
select
  seed.legacy_key, institutions.id, training_programs.id, seed.modality,
  seed.duration, seed.certification, seed.campus, seed.shifts,
  seed.national_validity, seed.image_url, seed.badge, seed.display_order,
  seed.form_enabled, seed.whatsapp, seed.is_visible, seed.publication_status,
  seed.metadata
from (values
  ('centro-de-formacion-tucuman-monteros-auxiliar-administrativo', 'centro-de-formacion-tucuman-monteros', 'auxiliar-administrativo', 'Presencial', '3 años', 'Auxiliar Administrativo', 'Rivadavia 295, Monteros', 'Consultar', 'Sí', 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1200&q=80', 'Inscripciones abiertas', 1, true, null, true, 'published', '{}'::jsonb),
  ('centro-de-formacion-tucuman-monteros-secretariado', 'centro-de-formacion-tucuman-monteros', 'secretariado', 'Presencial', '3 años', 'Secretariado', 'Rivadavia 295, Monteros', 'Consultar', 'Sí', 'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&w=1200&q=80', 'Nueva carrera', 2, true, null, true, 'published', '{}'::jsonb),
  ('centro-de-formacion-tucuman-monteros-operador-de-pc', 'centro-de-formacion-tucuman-monteros', 'operador-de-pc', 'Presencial', '3 años', 'Operador de PC', 'Rivadavia 295, Monteros', 'Consultar', 'Sí', 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80', 'Próximo ingreso', 3, true, null, true, 'published', '{}'::jsonb)
) as seed(
  legacy_key, institution_legacy_key, training_program_slug, modality, duration,
  certification, campus, shifts, national_validity, image_url, badge,
  display_order, form_enabled, whatsapp, is_visible, publication_status, metadata
)
join public.institutions on institutions.legacy_key = seed.institution_legacy_key
join public.training_programs on training_programs.slug = seed.training_program_slug;

do $seed_validation$
declare
  actual_count bigint;
begin
  select count(*) into actual_count from public.cities;
  if actual_count <> 3 then raise exception 'Expected 3 cities, found %', actual_count; end if;
  select count(*) into actual_count from public.institutions;
  if actual_count <> 10 then raise exception 'Expected 10 institutions, found %', actual_count; end if;
  select count(*) into actual_count from public.career_masters;
  if actual_count <> 19 then raise exception 'Expected 19 career masters, found %', actual_count; end if;
  select count(*) into actual_count from public.academic_offerings;
  if actual_count <> 30 then raise exception 'Expected 30 academic offerings, found %', actual_count; end if;
  select count(*) into actual_count from public.training_programs;
  if actual_count <> 3 then raise exception 'Expected 3 training programs, found %', actual_count; end if;
  select count(*) into actual_count from public.training_offerings;
  if actual_count <> 3 then raise exception 'Expected 3 training offerings, found %', actual_count; end if;
  if exists (select 1 from public.career_masters where slug = 'licenciatura-en-administracion') then
    raise exception 'Legacy administration alias was inserted as a duplicate career master';
  end if;
  if (select count(*) from public.academic_offerings ao join public.career_masters cm on cm.id = ao.career_master_id where cm.slug = 'abogacia') <> 3 then
    raise exception 'Expected 3 Abogacia academic offerings';
  end if;
  if (select count(*) from public.academic_offerings ao join public.career_masters cm on cm.id = ao.career_master_id where cm.slug = 'diagnostico-por-imagenes') <> 2 then
    raise exception 'Expected 2 Diagnostico por Imagenes academic offerings';
  end if;
  if exists (select 1 from public.training_offerings t join public.institutions i on i.id = t.institution_id where i.legacy_key = 'academia-profesional-norte-aguilares') then
    raise exception 'Academia Profesional Norte must not have training offerings';
  end if;
end;
$seed_validation$;
